# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

(1..2).each do |i|
	config.vm.define "node#{i}" do |node|
		node.vm.box = "centos/7"
		#node.vm.box = "geerlingguy/centos7"
		#node.vm.synced_folder ".", "/mnt/vagrant"
		node.vm.provider "virtualbox" do |vbox|
			vbox.name = "node#{i}"
			vbox.memory = 512
			vbox.cpus = 2
		end
		node.vm.network "private_network", ip: "172.16.101.1#{i}"
		node.vm.hostname = "node#{i}.cluster.lab"
		node.vm.provision "ansible" do |ansible|
			ansible.playbook = "cluster.yml"
		end
	end
end
end
