# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

(1..2).each do |i|
	config.vm.define "node#{i}" do |node|
		node.vm.box = "centos/7"
		node.vm.provider "virtualbox" do |vbox|
			vbox.name = "node#{i}"
			vbox.memory = 768
			vbox.cpus = 2
		end
		node.vm.network "private_network", ip: "172.16.101.1#{i}"
		node.vm.hostname = "node#{i}.cluster.lab"
		node.vm.synced_folder "/mnt/vagrant/", "/mnt/vagrant/"
		node.vm.provision "ansible" do |ansible|
			ansible.playbook = "pacemaker.yml"
		end
	end
end
end
