---
- hosts: all
become: yes
become_user: root
tasks:
	- name: Update packages
	yum: name=* state=latest
        - name: Install basic packages
        yum: name=bash-completion,vim,lsof,tcpdump,tree,bind-utils state=latest
        - name: Set SELINUX to Permissive
        selinux: policy=targeted state=permissive
        - name: Install Firewalld
        yum: name=firewalld state=latest
        - name: Enable Firewalld
        service: name=firewalld enabled=yes
        - yum: Install FreeIPA packages
        yum: name=ipa-server,ipa-server-dns,bind,bind-dyndb-ldap
