---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Install basic packages
    yum: state=latest name={{ item }}
    with_items:
      - bash-completion
      - vim
      - lsof
      - tcpdump
      - tree
      - bind-utils
  
  - name: Set SELINUX to permissive
    selinux: policy=targeted state=permissive
  - name: Install Firewalld
    yum: name=firewalld state=latest
  - name: Enable firewalld
    service: name=firewalld enabled=yes
  - name: Install FreeIPA server packages
    yum: name=[ 'ipa-server', 'ipa-server-dns', 'bind', 'bind-dyndb-ldap' ] state=latest
  - name: Open firewall for FreeIPA's ports
    command: firewall-cmd --add-service={ssh,dns,freeipa-ldap,freeipa-ldaps,freeipa-replication} --permanent
  - name: Reload firewall rules
    command: firewall-cmd --reload
...
