# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

(1..3).each do |i|
	config.vm.define "ipa#{i}" do |ipa|
		ipa.vm.box = "fedora/24-cloud-base"
		ipa.vm.provider "virtualbox" do |vbox|
			vbox.name = "ipa#{i}"
			vbox.memory = 1768
			vbox.cpus = 2
		end
		ipa.vm.network "private_network", ip: "172.16.101.1#{i}"
		ipa.vm.hostname = "ipa#{i}.freeipa.lab"
		ipa.vm.provision "ansible" do |ansible|
			ansible.playbook = "freeipa.yml"
		end
	end
end
end
