# -*- mode: ruby -*-
# vi: set ft=ruby :

# Settings to start up a laboratory in order to practice and get ready for the
# Red Hat Certified Engineer (RHEL7) Exam - EX300
# This Vagrantfile starts 2 nodes (Server and Client) with CentOS 7

Vagrant.configure(2) do |config|

(1..2).each do |i|
	config.vm.define "node#{i}" do |node|
		node.vm.box = "geerlingguy/centos7"
		node.vm.provider "virtualbox" do |vbox|
			vbox.name = "node#{i}"
			vbox.memory = 512
			vbox.cpus = 2
			node.vm.synced_folder ".", "/mnt/vagrant"
		end
		node.vm.network "private_network", ip: "172.16.1.1#{i}"
		node.vm.hostname = "node#{i}.rhce.lab"
		node.vm.provision "shell",
			inline: "sudo su -; who am i; yum update -y; yum install -y bash-completion vim lsof tcpdump tree bind-utils; setenforce Permissive; getenforce; sed -i 's/SELINUX=enforcing/SELINUX=permissive/' /etc/sysconfig/selinux; systemctl enable firewalld.service; systemctl start firewalld.service; yum repolist"
		end
	end
end
