# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.define "node1.dns.lab" do |node|
		node.vm.box = "centos/7"
		node.vm.provider "virtualbox" do |vbox|
			vbox.name = "node1.dns.lab"
			vbox.memory = 512
			vbox.cpus = 2
		end
		node.vm.network "private_network", ip: "172.16.101.11"
		node.vm.hostname = "node1.dns.lab"
		node.vm.provision "ansible" do |ansible|
			ansible.playbook = "bind-master.yml"
		end
	end
		config.vm.define "node2.dns.lab" do |node|
			node.vm.box = "centos/7"
			node.vm.provider "virtualbox" do |vbox|
				vbox.name = "node2.dns.lab"
				vbox.memory = 512
				vbox.cpus = 2
			end
			node.vm.network "private_network", ip: "172.16.101.12"
			node.vm.hostname = "node2.dns.lab"
			node.vm.provision "ansible" do |ansible|
				ansible.playbook = "bind-slave.yml"
			end
		end           
end
